version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      # Volume de dados
      - dados:/var/lib/postgres/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql